### ISSUE TITLE
Hamburger in mobile view not functional

### ISSUE THREAD

**Issue by ghost** [sami-ul-haq/psd-to-html#1]
The hamburger icon in mobile view is not functional. It does not show the nav items upon click. Add the dropdown to it with respective fields. It is probably a minor bug that's causing the dropdown not to open

**Comment by sami-ul-haq** [comment]
> The hamburger icon in mobile view is not functional. It does not show the nav items upon click. Add the dropdown to it with respective fields. It is probably a minor bug that's causing the dropdown not to open

Fixed, Working Now.
